pub(crate) mod agent_module_migration;
pub mod aggregation;
pub(crate) mod budget_alert;
pub mod budget_migration;
pub(crate) mod claude_oauth;
pub(crate) mod cli_probe;
pub(crate) mod cost_backfill_migration;
pub(crate) mod cursor_migration;
pub mod dashboard;
pub mod ingestion;
pub mod metering;
pub(crate) mod migration;
pub(crate) mod module_migration;
pub(crate) mod provider_pricing_migration;
pub(crate) mod quota_retry_migration;
pub(crate) mod rhythm;
pub mod session;
pub(crate) mod source_roots;
pub mod sql_helpers;
pub mod status;
pub(crate) mod subscription_pace;
pub(crate) mod system_provider_migration;
pub(crate) mod system_providers;
pub mod tray_snapshot;
pub mod tray_usage;
pub mod tray_usage_scheduler;
pub mod usage_cache;
pub(crate) mod usage_light_prediction;
pub(crate) mod usage_light_prediction_migration;
pub mod usage_stats;
pub(crate) mod watcher;
// watcher_state:生产路径只使用 begin_due/finish/mark_* 等子集;其余 getter 与
// set_interval 由模块内单元测试覆盖,非测试构建下允许未被引用(dead_code)。
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) mod watcher_state;
